import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // New token names (design handoff)
        "bg-0": "var(--bg-0)",
        "bg-1": "var(--bg-1)",
        "bg-2": "var(--bg-2)",
        "bg-3": "var(--bg-3)",
        "bg-4": "var(--bg-4)",
        "border-1": "var(--border-1)",
        "border-2": "var(--border-2)",
        "border-3": "var(--border-3)",
        "fg-1": "var(--fg-1)",
        "fg-2": "var(--fg-2)",
        "fg-3": "var(--fg-3)",
        "fg-4": "var(--fg-4)",
        "gold-1": "var(--gold-1)",
        "gold-2": "var(--gold-2)",
        "gold-3": "var(--gold-3)",
        "gold-4": "var(--gold-4)",
        ember: "var(--ember)",
        "ember-dim": "var(--ember-dim)",
        horde: "var(--horde)",
        "horde-dim": "var(--horde-dim)",
        alliance: "var(--alliance)",
        "alliance-dim": "var(--alliance-dim)",
        good: "var(--good)",
        warn: "var(--warn)",
        bad: "var(--bad)",
        info: "var(--info)",
        // Legacy aliases — keep existing screens working
        background: "var(--bg-0)",
        surface: "var(--bg-1)",
        "surface-elevated": "var(--bg-2)",
        border: "var(--border-1)",
        primary: "var(--gold-1)",
        "primary-hover": "var(--gold-2)",
        "text-primary": "var(--fg-1)",
        "text-secondary": "var(--fg-2)",
        success: "var(--good)",
        warning: "var(--warn)",
        error: "var(--bad)",
        "tier-verified": "var(--tier-verified)",
        "tier-high": "var(--tier-high)",
        "tier-medium": "var(--tier-medium)",
        "tier-low": "var(--tier-low)",
        "tier-research": "var(--tier-research)",
      },
      fontFamily: {
        sans: [
          "Inter",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        display: ["Cinzel", "Georgia", "serif"],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "monospace",
        ],
      },
      borderRadius: {
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        xl: "var(--r-xl)",
      },
    },
  },
  plugins: [],
};
export default config;
